### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by teijosol** [mprencipe/waggers#14]
I'm running waggers in github actions like this:

```
    steps:
      - name: Fuzz
        uses: mprencipe/waggers-action@v4
        with:
          url: https://rata-beta.digitraffic.fi/swagger/openapi.json
          fuzzcount: 5
```

This will end in the following error:
```
\ \/ \/ /\__  \   / ___\ / ___\_/ __ \_  __ \/  ___/
 \     /  / __ \_/ /_/  > /_/  >  ___/|  | \/\___ \ 
  \/\_/  (____  /\___  /\___  / \___  >__|  /____  >
              \//_____//_____/      \/           \/                                                   
panic: runtime error: index out of range [1] with length 1

goroutine 10 [running]:
main.fuzz({0xc0000b1a80, 0x75}, {0xc0000841e0, 0x1, 0xc0001ecfd0?}, 0xc000092c90, 0xc0000833e0, 0x9?)
	/Users/massimo.prencipe/projects/hobby/waggers/main.go:111 +0x454
created by main.main in goroutine 1
	/Users/massimo.prencipe/projects/hobby/waggers/main.go:233 +0xc9c
```
